# Site
title: 'Nikroblog'
description: 'Posts mostly around artifical intelligence and science.'
baseurl: '/blog'  # uncomment for 'github', comment for 'local'
# baseurl: ''
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
email: 'nikan.doosti@outlook.com'
google_analytics:
theme: jekyll-theme-midnight

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      permalink: post/:title/
      avatar: /assets/images/avatar1.jpg

