theme: jekyll-theme-midnight

# Site
name: 'Nikronic Blog'
description: 'Blogs and posts around mostly around artifical intelligence and science in general.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
email: 'nikan.doosti@outlook.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      permalink: post/:title/
      avatar: /assets/images/avatar1.jpg


# Paginate
paginate: 10
