theme: jekyll-theme-midnight

# Site
title: 'Nikroblog'
description: 'Nikronic's posts mostly around artifical intelligence and science.'
baseurl: '/blog'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
email: 'nikan.doosti@outlook.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      permalink: post/:title/
      avatar: /assets/images/avatar1.jpg

