# This is a basic workflow to help you get started with Actions

name: Copy _site/navigation.html to nikronic.github.io/_data/navigation.yml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: outside-interact
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Push a file to another repository
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: '_site/navigation/index.html'
          destination_repo: 'Nikronic/nikronic.github.io'
          destination_branch: 'master'
          destination_folder: '_data'
          user_email: 'nikan.doosti@outlook.com'
          user_name: 'Nikronic'
          commit_message: 'Automated commit trigged by push event on `blog` repo'

